name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast-scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Security Gate
        run: semgrep scan --config=auto --error

  container-scan-and-push:
    name: Docker Build, Trivy Scan & Registry Push
    needs: sast-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image Locally
        run: |
          docker build -t local-app:latest .

      - name: Run Trivy Security Scan Gate
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'local-app:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push to Local Registry
        if: success()
        run: |
          echo "All SAST & Container security gates PASSED successfully."
          docker tag local-app:latest 192.168.56.50:5000/juice-shop:latest
